### ISSUE TITLE
NoSuchBeanDefinitionException: No bean named 'systemService' is defined

### ISSUE THREAD

**Issue by liudonghua123** [zhangdaiscott/jeewx#1]
导入数据之后，修改以下两个配置文件中相应的用户名密码信息
```
src/main/resources/dbconfig.properties
src/main/resources/jeecg/jeecg_database.properties
```

双击 `start.bat` 或 切换到jeewx子目录下直接运行 `mvn tomcat:run` 都会提示 `NoSuchBeanDefinitionException: No bean named 'systemService' is defined`

完整的错误日志信息如下：

```bash
D:\code\lch\jeewx\jeewx>mvn tomcat:run
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.jeecgframework:jeewx-os:war:3.1.0
[WARNING] 'dependencies.dependency.systemPath' for org.jeewxframework:codegenerate-tmp:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/codegenerate-tmp-3.4.7-20180320.jar will be unresolvable by dependent
projects @ line 130, column 25
[WARNING] 'dependencies.dependency.systemPath' for org.jeecgframework:minidao-pe:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/minidao-pe-1.6.3-20180320.jar will be unresolvable by dependent projects @ line 137, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.ckfinder:CKFinder-updateByAlexander:jar should not point at files within the
project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/CKFinder-updateByAlexander-2.4-20170917.jar will be unresolvable by dependent projects @ line 159, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.ckfinder:CKFinderPlugin-FileEditor:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/CKFinderPlugin-FileEditor-2.4-20170917.jar will be unresolvable by
dependent projects @ line 166, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.ckfinder:CKFinderPlugin-ImageResize:jar should not point at files within the
project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/CKFinderPlugin-ImageResize-2.4-20170917.jar will be unresolvable by dependent projects @ line 173, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.ckfinder:CKFinderPlugin-Watermark:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/CKFinderPlugin-Watermark-2.4-20170917.jar will be unresolvable by dependent projects @ line 180, column 25
[WARNING] 'dependencies.dependency.systemPath' for pinyin4j:pinyin4j:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/pinyin4j-2.5.0-20170917.jar will be unresolvable by dependent projects @ line 201, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.springsource:org.quartz:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/org.quartz-1.6.2-20170917.jar will be unresolvable by dependent projects @ line 209, column 25
[WARNING] 'dependencies.dependency.systemPath' for org.jeewx:p3-extend:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/p3-extend-1.0-20151226.jar will be unresolvable by dependent projects @ line 354, column 23
[WARNING] 'dependencies.dependency.systemPath' for org.jeecgframework:jackson:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/jackson-1.84-20170917.jar will be unresolvable by dependent projects @ line 442, column 25
[WARNING] 'dependencies.dependency.systemPath' for org.artofsolving:jodconverter:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/jodconverter-3.0-beta-4-20170917.jar will be unresolvable by dependent projects @ line 646, column 25
[WARNING] 'dependencies.dependency.systemPath' for org.jeecg:jacob:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/jacob-1.0.0-20170917.jar will be unresolvable by dependent projects @ line 677, column 25
[WARNING] 'dependencies.dependency.systemPath' for org.jeecgframework:org.jeecgframework.batik-all:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/batik-all-1.7-20170917.jar will be unresolvable by dependent projects @ line 685, column 23
[WARNING] 'dependencies.dependency.systemPath' for org.jeecgframework:fop:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/fop-1.0-20170917.jar will be unresolvable by dependent projects @ line 692, column
23
[WARNING] 'dependencies.dependency.systemPath' for com.baidu.bcs:baidu-sdk:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/baidu-sdk-1.4.5-20170917.jar will be unresolvable by dependent projects @ line 736, column 25
[WARNING] 'dependencies.dependency.systemPath' for org.jeecgframework:alipay-sdk-java20161012120106:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/alipay-sdk-java20161012120106-1.0.jar will be unresolvable by dependent projects @ line 762, column 23
[WARNING] 'dependencies.dependency.systemPath' for org.jeewx:jeewx-api:jar should not point at files within the project directory, ${project.basedir}/src/main/webapp/WEB-INF/lib/jeewx-api-1.2.0-20180330.jar will be unresolvable by dependent projects @ line 770, column 23
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 832, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] --------------------< org.jeecgframework:jeewx-os >---------------------
[INFO] Building jeewx-os 3.1.0
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] >>> tomcat-maven-plugin:1.1:run (default-cli) > compile @ jeewx-os >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jeewx-os ---
[WARNING] Using platform encoding (GBK actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 36 resources
[INFO] Copying 60 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jeewx-os ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< tomcat-maven-plugin:1.1:run (default-cli) < compile @ jeewx-os <<<
[INFO]
[INFO]
[INFO] --- tomcat-maven-plugin:1.1:run (default-cli) @ jeewx-os ---
[INFO] Running war on http://localhost:80/jeewx
[INFO] Using existing Tomcat server configuration at D:\code\lch\jeewx\jeewx\target\tomcat
May 25, 2018 1:04:07 PM org.apache.catalina.startup.Embedded start
INFO: Starting tomcat server
May 25, 2018 1:04:07 PM org.apache.catalina.core.StandardEngine start
INFO: Starting Servlet Engine: Apache Tomcat/6.0.29
May 25, 2018 1:04:10 PM org.apache.catalina.core.ApplicationContext log
INFO: Set web app root system property: 'jeewx' = [D:\code\lch\jeewx\jeewx\src\main\webapp\]
May 25, 2018 1:04:10 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing log4j from [classpath:log4j.properties]
May 25, 2018 1:04:10 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
[org.springframework.web.context.ContextLoader]Root WebApplicationContext: initialization started
[org.springframework.web.context.support.XmlWebApplicationContext]Refreshing Root WebApplicationContext: startup date [Fri May 25 13:04:10 CST 2018]; root of context hierarchy
[org.springframework.beans.factory.support.DefaultListableBeanFactory]Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@14924f41: defining beans []; root of factory hierarchy
[org.springframework.web.context.ContextLoader]Root WebApplicationContext: initialization completed in 139 ms
May 25, 2018 1:04:10 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.jeecgframework.web.system.listener.InitListener
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'systemService' is defined
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:529)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1095)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:277)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1093)
        at org.jeecgframework.web.system.listener.InitListener.contextInitialized(InitListener.java:28)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4135)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4630)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
        at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
        at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
        at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
        at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
        at org.codehaus.mojo.tomcat.AbstractRunMojo.startContainer(AbstractRunMojo.java:558)
        at org.codehaus.mojo.tomcat.AbstractRunMojo.execute(AbstractRunMojo.java:255)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

May 25, 2018 1:04:10 PM org.apache.catalina.core.StandardContext start
SEVERE: Error listenerStart
May 25, 2018 1:04:10 PM org.apache.catalina.core.StandardContext start
SEVERE: Context [/jeewx] startup failed due to previous errors
May 25, 2018 1:04:10 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
[org.springframework.web.context.support.XmlWebApplicationContext]Closing Root WebApplicationContext: startup date [Fri May 25 13:04:10 CST 2018]; root of context hierarchy
[org.springframework.beans.factory.support.DefaultListableBeanFactory]Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@14924f41: defining beans []; root of factory hierarchy
May 25, 2018 1:04:10 PM org.apache.catalina.core.ApplicationContext log
INFO: Shutting down log4j
May 25, 2018 1:04:10 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/jeewx] registered the JBDC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
May 25, 2018 1:04:10 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/jeewx] registered the JBDC driver [com.alibaba.druid.mock.MockDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
May 25, 2018 1:04:10 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/jeewx] registered the JBDC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
May 25, 2018 1:04:10 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/jeewx] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to
stop it. This is very likely to create a memory leak.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.931 s
[INFO] Finished at: 2018-05-25T13:04:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:tomcat-maven-plugin:1.1:run (default-cli) on project jeewx-os: Could not start Tomcat: Protocol handler initialization failed: java.net.BindException: Address already in use: JVM_Bind <null>:80 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


```

**Comment by zhangdaiscott** [comment]
不支持jdk7
